zsh: move up conda init defs so auto-switching can work on a new shell
Problem: When we open a new (interactive) shell, automatic activation of
conda environment (by zsh-autoswitch-virtualenv) does not work with the
following error:

    CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
    To initialize your shell, run

        $ conda init <SHELL_NAME>

    ...

This is because by the (early) time when zsh-autoswitch-virtualenv is
executed during initializing the shell, the `conda` shell function which
initializes conda lazily is not defined. Instead, a non-shell executable
`$CONDA_EXE/condabin/conda` will be picked up.

Solution: Move up the definition of conda() init function and let it be
executed before sourcing zsh/antidote plugins.